### ISSUE TITLE
Can't open a world. Just installed the program for the first time.

### ISSUE THREAD

**Issue by GG-Cannon** [averi-studios/world-scribe-2-desktop#19]
Can't open a world.
-When creating a world, I get a result "Failed to connect to newly-created World"
-When trying to open a world, I get an error prompt 
"Uncaught Exception:
Error:SQLITE_CANTOPEN: Unable to open database file

**Steps to Reproduce**

I literally just installed the .exe in windows 10 and tried to create a world

**Expected behavior**
To create and open a world.

**Actual behavior**
Unknown error not allowing to open the world.

**Screenshots**
![image](https://user-images.githubusercontent.com/23584356/133356689-5d09aae7-6e31-425e-a736-a8e96fed8f9c.png)

**Your environment (please complete the following information):**

 - OS: Windows
 - App Version: 1.0.2.
 - Affected components: Non-UI, I think

**Additional context**
Literally just installed the program.

**Logs**
[2021-09-14 22:29:48.296] [info]  World Scribe 2 Server is now running at http://localhost:49000
[2021-09-14 22:30:27.882] [error] Error: ENOENT: no such file or directory, scandir 'C:\Users\Gabriel Jack\Desktop\Stories\WorldScribe\Worlds'
    at Object.readdirSync (fs.js:1021:3)
    at Object.e.readdirSync (electron/js2c/asar_bundle.js:5:10249)
    at C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\world-scribe-2-server\routes\world.js:114:33
    at Layer.handle [as handle_request] (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\express\lib\router\index.js:275:10)
[2021-09-14 22:30:43.283] [info]  SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:66:63)
[2021-09-14 22:31:55.582] [info]  SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:66:63)
[2021-09-14 22:32:22.913] [info]  Connecting to database...
[2021-09-14 22:32:31.139] [info]  World Scribe 2 Server is now running at http://localhost:49000
[2021-09-14 22:32:31.235] [info]  Checking for update
[2021-09-14 22:32:31.254] [info]  Generated new staging user ID: e6f53c6c-1c25-5416-8835-02293ecac9cd
[2021-09-14 22:32:34.802] [info]  Update for version 1.0.2 is not available (latest version: 1.0.2, downgrade is disallowed).
[2021-09-14 22:32:34.803] [info]  Update not available
[2021-09-14 22:32:34.803] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-09-14 22:32:49.852] [info]  Connecting to database...
[2021-09-14 22:33:12.564] [info]  World Scribe 2 Server is now running at http://localhost:49000
[2021-09-14 22:33:12.639] [info]  Checking for update
[2021-09-14 22:33:15.635] [info]  Update for version 1.0.2 is not available (latest version: 1.0.2, downgrade is disallowed).
[2021-09-14 22:33:15.636] [info]  Update not available
[2021-09-14 22:33:15.637] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-09-14 22:33:27.883] [info]  SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:66:63)
[2021-09-14 22:33:38.577] [info]  Connecting to database...
[2021-09-14 22:35:15.473] [info]  World Scribe 2 Server is now running at http://localhost:49000
[2021-09-14 22:35:15.592] [info]  Checking for update
[2021-09-14 22:35:18.999] [info]  Update for version 1.0.2 is not available (latest version: 1.0.2, downgrade is disallowed).
[2021-09-14 22:35:19.000] [info]  Update not available
[2021-09-14 22:35:19.001] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-09-14 22:35:20.298] [info]  Connecting to database...
[2021-09-14 22:36:45.266] [info]  World Scribe 2 Server is now running at http://localhost:49000
[2021-09-14 22:36:45.343] [info]  Checking for update
[2021-09-14 22:36:48.278] [info]  Update for version 1.0.2 is not available (latest version: 1.0.2, downgrade is disallowed).
[2021-09-14 22:36:48.279] [info]  Update not available
[2021-09-14 22:36:48.280] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-09-14 22:37:19.567] [info]  SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:66:63)
[2021-09-14 22:39:25.511] [info]  World Scribe 2 Server is now running at http://localhost:49000
[2021-09-14 22:39:25.584] [info]  Checking for update
[2021-09-14 22:39:29.000] [info]  Update for version 1.0.2 is not available (latest version: 1.0.2, downgrade is disallowed).
[2021-09-14 22:39:29.001] [info]  Update not available
[2021-09-14 22:39:29.002] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-09-14 22:39:52.315] [info]  SequelizeConnectionError: SQLITE_CANTOPEN: unable to open database file
    at Database.<anonymous> (C:\Users\Gabriel Jack\AppData\Local\Programs\world-scribe-2-desktop\resources\app.asar\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:66:63)
[2021-09-14 22:41:09.719] [info]  Connecting to database...
[2021-09-14 22:44:47.019] [info]  World Scribe 2 Server is now running at http://localhost:49000
[2021-09-14 22:44:47.095] [info]  Checking for update
[2021-09-14 22:44:50.572] [info]  Update for version 1.0.2 is not available (latest version: 1.0.2, downgrade is disallowed).
[2021-09-14 22:44:50.573] [info]  Update not available
[2021-09-14 22:44:50.574] [debug] checkForUpdatesAndNotify called, downloadPromise is null
[2021-09-14 22:45:33.813] [info]  Checking for update

**Comment by MarquisLP** [comment]
Hey @Gabriel-Jack, sorry to hear that you're immediately facing issues with the app! It looks like the app is having trouble opening the database for your newly-created world. Can you please go to this location on your computer:

`C:\Users\Gabriel Jack\Desktop\Stories\WorldScribe\Worlds`

and let me know if there's a file named "database" or "database.sqlite" in there? (If the "WorldScribe" and/or "Worlds" folder doesn't exist, please let me know as well.)
